# Generated by Django 5.1.2 on 2024-10-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, verbose_name='идентификатор')),
                ('email', models.EmailField(max_length=200, verbose_name='электронная почта')),
                ('first_name', models.CharField(max_length=500, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=500, verbose_name='last_name')),
                ('avatar', models.URLField(verbose_name='avatar')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='UserSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('text', models.CharField(max_length=500, verbose_name='text')),
                ('user_profile', models.ManyToManyField(related_name='user_supports', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Поддержка',
                'verbose_name_plural': 'Поддержка',
            },
        ),
    ]
